purchasemanager/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static


from . import views

app_name = 'purchasemanager'

patterns = [

	# # # DEFAULT

	url(r'^$', views.purchases.index, name='index'),

    # # # PURCHASES

    url(r'^purchase/new/$', views.purchases.new_purchase, name='new_purchase'),
    url(r'^purchase/all/$', views.purchases.all_purchases, name='all_purchases'),
    url(r'^purchase/draft/$', views.purchases.draft_purchases, name='draft_purchases'),
    url(r'^purchase/paid/$', views.purchases.paid_purchases, name='paid_purchases'),
    url(r'^purchase/unpaid/$', views.purchases.unpaid_purchases, name='unpaid_purchases'),
    url(r'^purchase/(?P<purchase_id>[0-9]+)/$', views.purchases.purchase, name='purchase'),
    url(r'^purchase/search/$', views.purchases.search_purchase, name='search_purchase'),
    url(r'^purchase/(?P<purchase_id>[0-9]+)/update/$', views.purchases.update_purchase, name='update_purchase'),
    url(r'^purchase/(?P<purchase_id>[0-9]+)/print/$', views.purchases.print_purchase, name='print_purchase'),
    url(r'^purchase/(?P<purchase_id>[0-9]+)/delete/$', views.purchases.delete_purchase, name='delete_purchase'),

    # # # ITEMS

    url(r'^purchase/(?P<purchase_id>[0-9]+)/item/add/$', views.items.add_item, name='add_item'),
    url(r'^purchase/(?P<purchase_id>[0-9]+)/item/(?P<purchaseitem_id>[0-9]+)/delete/$', views.items.delete_item, name='delete_item'),

    # # # PURCHASE EXPENSES

    url(r'^purchase/(?P<purchase_id>[0-9]+)/expenses/add/$', views.expenses.add_purchase_expense, name='add_purchase_expense'),
    url(r'^purchase/(?P<purchase_id>[0-9]+)/expenses/(?P<expense_id>[0-9]+)/delete/$', views.expenses.delete_purchase_expense, name='delete_purchase_expense'),

    # # # BUSINESS EXPENSES

    url(r'^expenses/$', views.expenses.expense_list, name='expense_list'),
    url(r'^expenses/new/$', views.expenses.new_business_expense, name='new_business_expense'),
    url(r'^expenses/(?P<expense_id>[0-9]+)/delete/$', views.expenses.delete_business_expense, name='delete_business_expense'),

    # # # REPORTS

    url(r'^accounting/$', views.reports.accounting, name='accounting'),

    # # # ATTACHMENTS

    url(r'^purchase/(?P<purchase_id>[0-9]+)/attachments/add/$', views.purchases.upload_purchase_attachment, name='upload_purchase_attachment'),
    url(r'^purchase/(?P<purchase_id>[0-9]+)/attachments/(?P<purchaseattachment_id>[0-9]+)/delete/$', views.purchases.delete_purchase_attachment, name='delete_purchase_attachment'),
    url(r'^expenses/(?P<expense_id>[0-9]+)/attachments/add/$', views.expenses.upload_business_expense_attachment, name='upload_business_expense_attachment'),

    # # # vendorS

    url(r'^vendors/$', views.vendors.vendor_list, name='vendor_list'),
    url(r'^vendor/(?P<vendor_id>[0-9]+)/$', views.vendors.vendor, name='vendor'),
	url(r'^vendor/(?P<vendor_id>[0-9]+)/update/$', views.vendors.update_vendor, name='update_vendor'),
    url(r'^vendor/(?P<vendor_id>[0-9]+)/delete/$', views.vendors.delete_vendor, name='delete_vendor'),
    url(r'^vendor/new/$', views.vendors.new_vendor, name='new_vendor'),


    # # # PRODUCTS

    url(r'^products/$', views.products.product_list, name='product_list'),
    url(r'^product/(?P<product_id>[0-9]+)/$', views.products.product, name='product'),
    url(r'^product/(?P<product_id>[0-9]+)/update/$', views.products.update_product, name='update_product'),
    url(r'^product/(?P<product_id>[0-9]+)/delete/$', views.products.delete_product, name='delete_product'),
    url(r'^product/new/$', views.products.new_product, name='new_product'),
    url(r'^ajax_calls/search/', views.products.autocompleteModel),


    # # # USER AUTHENTICATION

    url(r'^login/$', views.userauth.login_view, name='login'),
    url(r'^logout/$', views.userauth.logout_view, name='logout'),

    # # # ADMIN
	#url(r'^admin/$', admin.site.urls),
    url(r'^users/$', views.admin.users, name='users'),
    url(r'^settings/$', views.admin.settings, name='settings'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    url(r'^', include(patterns, namespace="purchasemanager")),
]

purchasemanager/models.py
from __future__ import unicode_literals

from django.core.files.storage import FileSystemStorage
from django.db import models

# Create your models here.
class Vendor(models.Model):
	name = models.CharField(max_length=256)
	address1 = models.CharField(max_length=256, blank=True)
	address2 = models.CharField(max_length=256, blank=True)
	atoll = models.CharField(max_length=256, blank=True)
	island = models.CharField(max_length=256, blank=True)
	email = models.CharField(max_length=256, blank=True)

	def __str__(self):
		return self.name

	def purchases(self):
		return Purchase.objects.filter(vendor=self).count()

class Product(models.Model):
	code = models.CharField(max_length=256)
	name = models.CharField(max_length=256)
	description = models.CharField(max_length=256, blank=True)
	unit = models.CharField(max_length=256, blank=True)

	def __str__(self):
		return self.code

class Purchase(models.Model):
	vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
	date = models.DateField()
	status = models.CharField(max_length=10)

	def __str__(self):
	    return str(self.id)

	def total_items(self):
		total = 0
		items = self.purchaseitem_set.all()

		for item in items:
			total += item.cost * item.qty

		return total

	def total_expenses(self):
		total = 0
		expenses = self.expense_set.all()

		for expense in expenses:
			total += expense.cost * expense.qty

		return total

	def total(self):
		items = self.total_items()
		expenses = self.total_expenses()

		return items - expenses

	def paid(self):
		return self.status == 'Paid'

	def unpaid(self):
		return self.status == 'Unpaid'

	def draft(self):
		return self.status == 'Draft'

class PurchaseItem(models.Model):
	purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)
	name = models.CharField(max_length=128)
	description = models.TextField()
	cost = models.DecimalField(decimal_places=2, max_digits=10)
	qty = models.IntegerField()

	def total(self):
		return self.cost * self.qty

class Expense(models.Model):
	description = models.TextField()
	cost = models.DecimalField(decimal_places=2, max_digits=10)
	qty = models.IntegerField()
	purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE, blank=True, null=True)
	date = models.DateField(blank=True, null=True)

	def total(self):
		return self.cost * self.qty

	def is_business_expense(self):
		return self.purchase is None

class PurchaseAttachment(models.Model):
	file = models.FileField(upload_to='purchase/')
	displayname = models.CharField(max_length=128)
	purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)

class ExpenseAttachment(models.Model):
	file = models.FileField(upload_to='expense/')
	displayname = models.CharField(max_length=128)
	expense = models.ForeignKey(Expense, on_delete=models.CASCADE)

purchasemanager/views/admin.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
import datetime

from purchasemanager.models import Vendor, Product, Purchase, PurchaseItem, Expense, PurchaseAttachment, ExpenseAttachment	
from django.contrib.auth.models import User




# Administrative settings
def users(request):
    return None #User.objects.all()


def settings(request):
    return None

purchasemanager/views/expenses.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
import datetime

from purchasemanager.models import Vendor, Purchase, PurchaseItem, Expense, PurchaseAttachment, ExpenseAttachment



# Add expense to purchase
@login_required(login_url='login/')
def add_purchase_expense(request, purchase_id):
	purchase = get_object_or_404(Purchase, pk=purchase_id)
	try:
		e = purchase.expense_set.create(description=request.POST['description'], cost=request.POST['cost'], qty=request.POST['qty'])
		e.save()
	except (KeyError, Purchase.DoesNotExist):
		return render(request, 'view_purchase.html', {
			'purchase': purchase,
			'error_message': 'Not all fields were completed.',
		})
	else:
		return HttpResponseRedirect(reverse('purchasemanager:purchase', args=(purchase.id,)))



# Delete expense from purchase
@login_required(login_url='login/')
def delete_purchase_expense(request, expense_id, purchase_id):
	expense = get_object_or_404(Expense, pk=expense_id)
	purchase = get_object_or_404(Purchase, pk=purchase_id)
	try:
		expense.delete()
	except (KeyError, Expense.DoesNotExist):
		return render(request, 'view_purchase.html', {
			'purchase': purchase,
			'error_message': 'Expense does not exist.',
		})
	else:
		return HttpResponseRedirect(reverse('purchasemanager:purchase', args=(purchase.id,)))

		

# List all business expenses (expense item with no purchase_id)
@login_required(login_url='login/')
def expense_list(request):
	expenses = Expense.objects.filter(purchase_id=None)
	context = {
		'expenses' : expenses,
	}
	return render(request, 'expenses.html', context)


		
# New business expense
@login_required(login_url='login/')
def new_business_expense(request):
	if request.method == 'POST':
		# Stuff from form
		date = datetime.datetime.strptime(request.POST['date'], "%m/%d/%Y")
		e = Expense(description=request.POST['description'], date=date, cost=request.POST['cost'], qty=request.POST['qty'])
		e.save()
		return HttpResponseRedirect(reverse('purchasemanager:expense_list'))
	else:
		return render(request, 'new_expense.html')
		
		
		
# Upload attachment for business expense
@login_required(login_url='login/')
def upload_business_expense_attachment(request, expense_id):
    # Get expense
    expense = get_object_or_404(Expense, pk=expense_id)
    
    if request.method == 'POST':
        # Get file from POST data
        myfile = request.FILES['file']
        
        # Save file to filesystem
        fs = FileSystemStorage()
        fs.save(myfile.name, myfile)
        
        # Create new ExpenseAttachment record
        e = expense.expenseattachment_set.create(file=myfile, displayname=myfile.name)
        e.save()
        
		# Redirect to expenses list
        return HttpResponseRedirect(reverse('purchasemanager:expense_list'))
    else:
        context = {
            'expense' : expense,
        }
        return render(request, 'upload_attachment.html', context)
	
	
	
# Delete attachment from business expense
@login_required(login_url='login/')
def delete_business_expense_attachment(request, expense_id, expenseattachment_id):
	expense = get_object_or_404(Expense, pk=expense_id)
	expenseattachment = get_object_or_404(ExpenseAttachment, pk=expenseattachment_id)
	try:
		expenseattachment.delete()
		fs = FileSystemStorage()
		fs.delete(expenseattachment)
	except:
		context = {
			'error_message' : "Unable to delete attachment!",
		}
		return render(request, 'expenses.html', context)
	else:
		return HttpResponseRedirect(reverse('purchasemanager:expense_list'))

		

# Delete business expense
@login_required(login_url='login/')
def delete_business_expense(request, expense_id):
	expense = get_object_or_404(Expense, pk=expense_id)
	try:
		expense.delete()
	except (KeyError, Expense.DoesNotExist):
		return render(request, 'expenses.html', {
			'error_message': 'Expense does not exist!',
		})
	else:
		return HttpResponseRedirect(reverse('purchasemanager:expense_list'))	

purchasemanager/views/items.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from purchasemanager.models import Vendor, Purchase, PurchaseItem, Expense, PurchaseAttachment, ExpenseAttachment



# Add purchaseitem to purchase
@login_required(login_url='login/')
def add_item(request, purchase_id):
	purchase = get_object_or_404(Purchase, pk=purchase_id)
	try:
		i = purchase.purchaseitem_set.create(name=request.POST['name'], description=request.POST['description'], cost=request.POST['cost'], qty=request.POST['qty'])
		i.save()
	except (KeyError, Purchase.DoesNotExist):
		return render(request, 'view_purchase.html', {
			'purchase': purchase,
			'error_message': 'Not all fields were completed.',
		})
	else:
		return HttpResponseRedirect(reverse('purchasemanager:purchase', args=(purchase.id,)))



# Delete purchaseitem from purchase
@login_required(login_url='login/')
def delete_item(request, purchaseitem_id, purchase_id):
	
	item = get_object_or_404(PurchaseItem, pk=purchaseitem_id)
	purchase = get_object_or_404(Purchase, pk=purchase_id)
	try:
		item.delete()
	except (KeyError, PurchaseItem.DoesNotExist):
		return render(request, 'view_purchase.html', {
			'purchase': purchase,
			'error_message': 'Item does not exist.',
		})
	else:
		return HttpResponseRedirect(reverse('purchasemanager:purchase', args=(purchase.id,)))

purchasemanager/views/products.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import datetime
from ajax_select.fields import AutoCompleteSelectMultipleField
import json

from purchasemanager.models import Vendor, Product, Purchase, PurchaseItem, Expense, PurchaseAttachment, ExpenseAttachment



# List all products
@login_required(login_url='login/')
def product_list(request):
	products = Product.objects.all()
	context = {
		'title' : 'Product List',
		'products' : products,
	}
	return render(request, 'products.html', context)
	
	
	
# Show specific product details
@login_required(login_url='login/')
def product(request, product_id):
	product = get_object_or_404(Product, pk=product_id)
	context = {
		'title' : "Product info - %s" % product.name,
		'product' : product,
	}
	return render(request, 'product.html', context)

# Show specific product details
@login_required(login_url='login/')
def autocompleteModel(request):
    if request.is_ajax():
        q = request.GET.get('term', '').capitalize()
        search_qs = Product.objects.filter(code__startswith=q)
        results = []
        print q
        for r in search_qs:
            results.append(r.code)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)	
	
# Add new product
@login_required(login_url='login/')
def new_product(request):
	if request.method == 'POST':
		# Stuff from form
		c = Product(code=request.POST['code'], name=request.POST['name'], description=request.POST['description'], unit=request.POST['unit'])
		c.save()
		return HttpResponseRedirect(reverse('purchasemanager:product_list'))
	else:
		return render(request, 'new_product.html')



# Update product
@login_required(login_url='login/')
def update_product(request, product_id):
	# Stuff from form
	c = get_object_or_404(Product, pk=product_id)
	
	c.code = request.POST['code']
	c.name = request.POST['name']
	c.description = request.POST['description']
	c.unit = request.POST['unit']

	
	c.save()
	
	return HttpResponseRedirect(reverse('purchasemanager:product', args=(c.id,)))

		
# Delete product
@login_required(login_url='login/')
def delete_product(request, product_id):
	product = get_object_or_404(Product, pk=product_id)
	product.delete()
	return HttpResponseRedirect(reverse('purchasemanager:product_list'))

purchasemanager/views/reports.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from itertools import chain
import datetime

from purchasemanager.models import Vendor, Purchase, PurchaseItem, Expense, PurchaseAttachment, ExpenseAttachment	



# Accounting report
@login_required(login_url='login/')
def accounting(request):
	if request.method == 'POST':
		start = datetime.datetime.strptime(request.POST['start'], "%m/%d/%Y")
		end = datetime.datetime.strptime(request.POST['end'], "%m/%d/%Y")
		
		if start > end:
			context = {
				'error_message' : "Start date must be before end date!",
			}
			return render(request, 'accounting.html', context)
		else:
			paidpurchases = Purchase.objects.filter(date__gt=start).filter(date__lt=end).filter(status = 'Paid')
			allpurchases = Purchase.objects.filter(date__gt=start).filter(date__lt=end)
			expenses = Expense.objects.filter(date__gt=start).filter(date__lt=end)
			
			# Sum of all paid purchases
			purchasetotal = 0
			for i in paidpurchases:
				purchasetotal += i.total_items()
				
			# Add purchase expenses within date range, regardless of purchase status
			for i in allpurchases:
				expenses = list(chain(expenses, Expense.objects.filter(purchase=i)))
			
			# Sum of all expenses
			expensetotal = 0
			for expense in expenses:
				expensetotal += expense.total()
			
			context = {
				'start' : start,
				'end' : end,
				'purchases' : paidpurchases,
				'expenses' : expenses,
				'purchasetotal' : purchasetotal,
				'expensetotal' : expensetotal,
				'nettotal' : purchasetotal - expensetotal,
			}
			return render(request, 'accounting.html', context)
	else:
		return render(request, 'accounting.html')

purchasemanager/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	{% if title %}
	<title>{{ title }}</title>
	{% else %}
	<title>E-Procurment</title>
	{% endif %}	
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  crossorigin="anonymous"></script>

	<link rel="stylesheet" href="https://code.jquery.com/ui/jquery-ui-git.css" type="text/css" media="all" /> 


	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
	
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">


</head>

<body>
	<nav class="navbar navbar-inverse navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'purchasemanager:index' %}"><strong>E-Procurement</strong></a>
			</div>
			
			{% if user.is_authenticated %}
			
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Purchases <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'purchasemanager:new_purchase' %}"><strong>New Purchase</strong></a></li>
							<li><a href="{% url 'purchasemanager:index' %}">Recent</a></li>
							<li class="divider" role="separator"></li>
							<li><a href="{% url 'purchasemanager:all_purchases' %}">List All</a></li>
							<li><a href="{% url 'purchasemanager:draft_purchases' %}">Draft Purchases</a></li>
							<li><a href="{% url 'purchasemanager:paid_purchases' %}">Paid Purchases</a></li>
							<li><a href="{% url 'purchasemanager:unpaid_purchases' %}">Unpaid Purchases</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Vendors <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'purchasemanager:new_vendor' %}"><strong>New Vendor</strong></a></li>
							<li role="separator" class="divider"></li>
							<li><a href="{% url 'purchasemanager:vendor_list' %}">List All</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Products <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'purchasemanager:new_product' %}"><strong>New Product</strong></a></li>
							<li role="separator" class="divider"></li>
							<li><a href="{% url 'purchasemanager:product_list' %}">List All</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Expenses <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'purchasemanager:new_business_expense' %}"><strong>New Expense</strong></a></li>
							<li role="separator" class="divider"></li>
							<li><a href="{% url 'purchasemanager:expense_list' %}">List All</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Reports <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'purchasemanager:accounting' %}">Accounting</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Admin <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'purchasemanager:users' %}">Users</a></li>
							<li><a href="{% url 'purchasemanager:settings' %}">Settings</a></li>
						</ul>
					</li>
				</ul>
				
				<form class="navbar-form navbar-right" action="{% url 'purchasemanager:search_purchase' %}" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Purchase Number" name="id">
					</div>
					<button type="submit" class="btn btn-default">Go</button>
				</form>
				
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Hello, {{ user.username }}</a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'purchasemanager:logout' %}">Logout</a></li>
						</ul>
					</li>
				</ul>
			</div>
			
			{% endif %}
			
		</div>
	</nav>
	
	<div class="container">

{% block content %}

{% endblock %}

	</div>
</body>

</html>

purchasemanager/templates/expenses.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<div class="alert alert-danger">{{ error_message }}</div>
{% endif %}

{% if expenses %}

<div class="panel panel-primary">
	<div class="panel-heading">Business expenses</div>
	<table class="table table-hover">
		<tr>
			<th>Description</th>
			<th>Date</th>
			<th>Cost</th>
			<th>Qty</th>
			<th>Total</th>
			<th>Attachment(s)</th>
			<th class="text-right">Actions</th>
		</tr>
		{% for expense in expenses %}
		<tr>
			<!-- ID: {{ expense.id }} -->
			<td>{{ expense.description }}</td>
			<td>{{ expense.date|date:"SHORT_DATE_FORMAT" }}</td>
			<td>${{ expense.cost }}</td>
			<td>{{ expense.qty }}</td>
			<td>${{ expense.total }}</td>
			<td>
				{% for attachment in expense.expenseattachment_set.all %}
				<a href="{{ attachment.file.url }}">{{ attachment.displayname }}</a><br>
				{% endfor %}
			</td>
			<td class="text-right">
				<a href="{% url 'purchasemanager:upload_business_expense_attachment' expense.id %}" class="btn btn-xs btn-default">Add Attachment</a>
				<button type="button" data-toggle="modal" data-target="#confirmdelete" data-object-name="{{ expense.description }}" data-delete-url="{% url 'purchasemanager:delete_business_expense' expense.id %}" class="btn btn-xs btn-danger">Delete</button>
			</td>
		</tr>
		{% endfor %}
	</table>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="confirmdelete" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Confirm</h4>
			</div>
			<div class="modal-body">
				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">No</button>
				<a href="#" class="btn btn-danger">Yes</a>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function() {
		$('#confirmdelete').on('show.bs.modal', function(e) {
			var name = $(e.relatedTarget).data('object-name');
			var url = $(e.relatedTarget).data('delete-url');
			$('#confirmdelete .modal-body').html("Are you sure you want to delete " + name + "?<br><i>Any associated attachments will also be deleted.</i>");
			$('#confirmdelete .modal-footer a').attr('href', url);
		});
	});
</script>
<!-- END delete confirmation modal -->

{% else %}

<div class="alert alert-warning">No business expenses!</div>

{% endif %}

{% endblock %}

purchasemanager/templates/login.html
{% extends 'base.html' %}

{% block content %}

<form method="post" action="{% url 'purchasemanager:login' %}" class="form-horizontal">
{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Please login</div>
		<div class="panel-body">

			<div class="form-group">
				<label class="col-sm-3 control-label" for="username">Username:</label>
				<div class="col-sm-6"><input type="text" name="username" class="form-control"></div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label" for="password">Password:</label>
				<div class="col-sm-6"><input type="password" name="password" class="form-control"></div>
			</div>
			
		</div>
		<div class="panel-footer">
			<input type="submit" value="Login" class="btn btn-primary">
		</div>
	</div>
</form>
{% endblock %}

purchasemanager/templates/new_purchase.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<div class="alert alert-danger">{{ error_message }}</div>
{% endif %}

{% if vendor_list %}

<form method="POST" action="{% url 'purchasemanager:new_purchase' %}" name="vendor" class="form-horizontal">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Select Vendor</div>
		<div class="panel-body">
			<div class="form-group">
				<label class="col-sm-3 control-label">Vendor:</label>
				<div class="col-sm-6">
					<select class="form-control" name="vendor_id">
						<option value="None">(Select)</option>
						{% for vendor in vendor_list %}
						<option value="{{ vendor.id }}">{{ vendor.name }}</option>
						{% endfor %}
					</select>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<a href="{% url 'purchasemanager:new_vendor' %}" class="btn btn-default">Add New Vendor</a>
			<input type="submit" value="Create Purchase" class="btn btn-primary">
		</div>
	</div>
</form>

{% else %}

<div class="alert alert-danger">No vendors!</div>

{% endif %}

{% endblock %}